version: '3.9'

services:
  postgres:
    image: postgres:15.4
    ports:
      - ${POSTGRES_PORT:-5433}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - tree

  redis:
    image: redis:7.2
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis-data:/data
    networks:
      - tree

  app:
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - ${PORT:-3000}:3000
    environment:
      REDIS_HOST: redis
      POSTRGRES_HOST: postgres
    networks:
      - tree

networks:
  tree:
    driver: bridge

volumes:
  redis-data:
  pg-data:
